@echo off
REM This batch file runs and plots data collected
REM by flux_log_aggregator.pl
REM
REM All files used below must be in the directory where
REM the STO files you want to process are located

REM ################################################
REM flux_log_aggregator.pl is looking for an input file
REM The input file contains values to be used for curve extrapolation
REM For example use the following if you have an input file: 
REM 	perl flux_log_aggregator.pl "my_input_values.txt"
REM If you don't provide any input file, the script will automatically
REM use extrapolation_values.txt
REM NOTE: DO NOT MODIFY extrapolation_values.txt
perl flux_log_aggregator.pl

REM ################################################
REM This is a perl script that breaks the output data file
REM generated by flux_log_aggregator.pl and generates new text
REM files named <element_name>-filtered.text
perl separate_element_data.pl

REM ################################################
REM adjust the input value here for plot_element_data.m
REM 	1 => plot BEP vs time for a user defined temperature/valve position
REM 	2 => plot temp/valve position vs. user-defined BEP
REM 	NOTE: the user must specify 1 or 2 to match with
REM 		  the input file used for flux_log_aggregator.pl
MATLAB -r plot_element_data(2)
